name: acrofs-project
on:
  push:
    branches:
     - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Side by Side testing
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - run: dotnet build Acrobit.AcroFS

      - run: dotnet test AcroFS.Tests

      - name: Create the package
        run: dotnet pack --configuration Release Acrobit.AcroFS

      - name: NuGet login (trusted publishing)
        uses: NuGet/login@v1
        id: login
        with:
          user: ghominejad

      - name: Publish the package to nuget.org
        run: dotnet nuget push "**/bin/Release/*.nupkg" -k ${{ steps.login.outputs.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
