name: acrofs-project
on:
  push:
    branches: 
     - test
     - master
jobs:
  build:
    runs-on: ubuntu-latest
    name: Side by Side testing
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          #dotnet-version: '5.0.x'
          dotnet-version: '6.0.x'
          include-prerelease: true

      - run: dotnet build Acrobit.AcroFS

      - run: dotnet test AcroFS.Tests

      - name: Create the package
        run: dotnet pack --configuration Release Acrobit.AcroFS

      - name: Publish the package to nuget.org
        run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
        env:
            NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
